apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-checkpoints-bucket
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: gcsfuse-bucket
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: mlops-checkpoints
  claimRef:
    name: model-checkpoints
    namespace: colorflow