apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: colorflow-mlflow
    newName: europe-west6-docker.pkg.dev/project-id/colorflow/colorflow-mlflow
    newTag: latest
  - name: colorflow-trainer
    newName: europe-west6-docker.pkg.dev/project-id/colorflow/colorflow-trainer
    newTag: latest
  - name: colorflow-ui
    newName: europe-west6-docker.pkg.dev/project-id/colorflow/colorflow-ui
    newTag: latest
  - name: colorflow-mlserver
    newName: europe-west6-docker.pkg.dev/project-id/colorflow/colorflow-mlserver
    newTag: latest
patches:
  - path: namespace-labels-patch.yaml
  - path: checkpoints-pvc-patch.yaml
  - path: ingress-host-patch.yaml