apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-artifacts-filestore
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    server: 10.60.111.146
    path: /colorflow
