apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: colorflow
spec:
  template:
    spec:
      containers:
        - name: mlflow
          env:
            - name: MLFLOW_ARTIFACT_ROOT
              value: gs://mlops-flow
