apiVersion: batch/v1
kind: Job
metadata:
  name: trainer
  namespace: colorflow
spec:
  template:
    spec:
      containers:
        - name: trainer
          env:
            - name: DVC_PULL_DATA
              value: "true"
            - name: DVC_PULL_TARGET
              value: images.dvc
