apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: colorflow-ui
    newTag: local
  - name: colorflow-mlserver
    newTag: local
patches:
  - path: namespace-labels-patch.yaml
  - path: checkpoints-pvc-patch.yaml
  - path: ingress-host-patch.yaml