apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/trainer
images:
  - name: colorflow-trainer
    newName: europe-west6-docker.pkg.dev/mlops-colorflow/colorflow/colorflow-trainer
    newTag: mlflow-timeout-fix-20260516
patches:
  - path: trainer-dvc-pull-patch.yaml
  - path: gcsfuse-annotation-patch.yaml
