apiVersion: batch/v1
kind: Job
metadata:
  name: trainer
  namespace: colorflow
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      containers:
        - name: trainer
          env:
            - name: COLORFLOW_CHECKPOINT_DIR
              value: /checkpoints
          volumeMounts:
            - name: checkpoints
              mountPath: /checkpoints
      volumes:
        - name: checkpoints
          persistentVolumeClaim:
            claimName: model-checkpoints