apiVersion: batch/v1
kind: Job
metadata:
  name: trainer
  namespace: colorflow
spec:
  template:
    spec:
      containers:
        - name: trainer
          args:
            - train.py
            - training.pretrain.enabled=false
            - training.epochs=1
            - data.batch_size=1
            - data.num_workers=2
            - data.image_size_1=128
            - data.image_size_2=128
            - data.external_data_size=2
            - data.train_size=1
          env:
            - name: COLORFLOW_DATA_DIR
              value: /app/storage/mlops-coco/images
            - name: GCS_DATA_URI
              value: gs://mlops-coco
